### ISSUE TITLE
当同一个页面存在多个编辑器实例时，右下角统计字符数不准确

### ISSUE THREAD

**Issue by kimsmel** [aieditor-team/AiEditor#106]
复现： [https://codepen.io/Kimmel-Wasser/pen/wvVrGgG](https://codepen.io/Kimmel-Wasser/pen/wvVrGgG)

现象描述：

当同一个页面存在多个编辑器实例时，第一个实例的统计字符数永远都会变成最后一个实例的统计字符数！

**Comment by naiheyoung** [comment]
当有多个实例时, 随意聚焦一个编辑器会触发所有实例的`textCounter`函数
且持续输入会连续触发`textCounter`函数 可以使用防抖函数进行优化

目前有一个方案可以解决你所描述的问题 重写每个实例统计字数的逻辑即可
```ts
new AiEditor({
    ...
    textCounter: (text) => text.length,
})
```
