### ISSUE TITLE
how to let the ai Bubble  menu do not show chinese

### ISSUE THREAD

**Issue by jiangsi** [aieditor-team/AiEditor#108]
when I new  a aieditor use lang='en'
the ai bubble menu  translate is show chinese word,how to change it ?

![image](https://github.com/user-attachments/assets/5eda1881-7864-4243-8222-88fc5b3852b9)

thanks for the awsome work

**Comment by yangfuhai** [comment]
This configuration refers to this document:  https://aieditor.dev/ai/translate.html
