### ISSUE TITLE
uploaderEvent的onUploadBefore

### ISSUE THREAD

**Issue by ashuicoder** [aieditor-team/AiEditor#11]
现在感觉onUploadBefore这个钩子没用，希望能做成return false就会阻止上传，比如图片上传的太大了就要取消上传

**Comment by yangfuhai** [comment]
这个钩子，主要用于去配置一些 http 头信息、授权信息等。

**Comment by yangfuhai** [comment]
已经添加 返回 false 停止上传的功能。
