### ISSUE TITLE
动态设置md内容时图片无法显示

### ISSUE THREAD

**Issue by KonngExplorer** [aieditor-team/AiEditor#111]
使用getMarkdown()获取的内容再次使用setMarkdownContent()动态设置内容时，图片无法正常解析显示。

示例图片：
`![avatar](https://miro.readmedium.com/v2/resize:fill:88:88/1*uTEzlRvlNBr3ralJoTQkmg.jpeg)`

官网demo测试，经典风格demo粘贴markdown图片无法显示，类腾讯文档风格却可以正常显示。
![image](https://github.com/user-attachments/assets/523903b0-9c5f-4e9e-aa07-2b70a6047a55)
![image](https://github.com/user-attachments/assets/0b7be4e7-b2fa-4039-b861-198e1262a03f)

**Comment by yangfuhai** [comment]
fixed
