### ISSUE TITLE
使用setMarkdownContent(value)插入markdown有序列表内容报错，有序列表序号不显示

### ISSUE THREAD

**Issue by 2919807875** [aieditor-team/AiEditor#117]
2index.vue:132 RangeError: Invalid content for node listItem: <>
    at fm.checkContent (index.js:1922:1)
    at xl.check (index.js:1325:1)
    at eval (index.js:1333:1)
    at w.forEach (index.js:311:1)
    at xl.check (index.js:1333:1)
    at eval (index.js:10541:1)
    at w.forEach (index.js:311:1)
    at eval (index.js:10540:1)
    at Object.eval [as insertContentAt] (index.js:9435:1)
    at eval (index.js:10437:1)

 "vue": "^2.6.14",

**Comment by yangfuhai** [comment]
具体错误的 markdown 内容是什么，请发一下

**Comment by 2919807875** [comment]
销售分析报告

## 一、概述

本报告旨在分析过去一季度的销售数据，以评估销售业绩并提出改进建议。

## 二、销售数据概览

1. **总销售额**：本季度总销售额为500万元，同比增长15%。
2. **销售渠道**：
   - 线上销售：300万元，占总销售额的60%。
   - 线下销售：200万元，占总销售额的40%。

## 三、产品分析

1. **畅销产品**：
   - 产品A：销售额150万元，市场占有率20%。
   - 产品B：销售额120万元，市场占有率15%。
   
2. **滞销产品**：
   - 产品C：销售额仅30万元，需进行促销活动。

## 四、客户分析

1. **客户群体**：
   - 新客户：占总客户的30%。
   - 老客户：占总客户的70%，忠诚度高。

2. **客户反馈**：
   - 产品质量满意度：85%。
   - 售后服务满意度：75%。

## 五、市场趋势

1. **行业增长**：整体市场增长率为10%，我司表现优于行业平均水平。
2. **竞争分析**：主要竞争对手的市场份额有所下降，为我司提供了扩展机会。

## 六、改进建议

1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
2. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
3. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。

## 七、结论

通过本次销售分析，我们发现了销售增长的潜力和改进的方向。希望通过实施建议，进一步提升销售业绩。


> 具体错误的 markdown 内容是什么，请发一下

**Comment by 2919807875** [comment]
> 具体错误的 markdown 内容是什么，请发一下

" 销售分析报告

## 一、概述

本报告旨在分析过去一季度的销售数据，以评估销售业绩并提出改进建议。

## 二、销售数据概览

1. **总销售额**：本季度总销售额为500万元，同比增长15%。
2. **销售渠道**：
   - 线上销售：300万元，占总销售额的60%。
   - 线下销售：200万元，占总销售额的40%。

## 三、产品分析

1. **畅销产品**：
   - 产品A：销售额150万元，市场占有率20%。
   - 产品B：销售额120万元，市场占有率15%。
   
2. **滞销产品**：
   - 产品C：销售额仅30万元，需进行促销活动。

## 四、客户分析

1. **客户群体**：
   - 新客户：占总客户的30%。
   - 老客户：占总客户的70%，忠诚度高。

2. **客户反馈**：
   - 产品质量满意度：85%。
   - 售后服务满意度：75%。

## 五、市场趋势

1. **行业增长**：整体市场增长率为10%，我司表现优于行业平均水平。
2. **竞争分析**：主要竞争对手的市场份额有所下降，为我司提供了扩展机会。

## 六、改进建议

1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
2. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
3. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。

## 七、结论

通过本次销售分析，我们发现了销售增长的潜力和改进的方向。希望通过实施建议，进一步提升销售业绩。" 这些

**Comment by yangfuhai** [comment]
这个 markdown 插入并不会出现错误呢，至于序号显示不了那是 makrdown 的格式问题 1.   2.  3.  之类的序号是无法显示的。

在 markdown 中， 以下的内容都是同一个含义：

```markdown
1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
2. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
3. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。


1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
1. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
1. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。



-  **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
-  **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
-  **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。

```

**Comment by 2919807875** [comment]
> 这个 markdown 插入并不会出现错误呢，至于序号显示不了那是 makrdown 的格式问题 1. 2. 3. 之类的序号是无法显示的。
> 
> 在 markdown 中， 以下的内容都是同一个含义：
> 
> ```
> 1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
> 2. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
> 3. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。
> 
> 
> 1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
> 1. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
> 1. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。
> 
> 
> 
> -  **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
> -  **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
> -  **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。
> ```

![image](https://github.com/user-attachments/assets/b86410cd-051f-4aa9-aaac-b054c466f31d)

**Comment by 2919807875** [comment]
> 这个 markdown 插入并不会出现错误呢，至于序号显示不了那是 makrdown 的格式问题 1. 2. 3. 之类的序号是无法显示的。
> 
> 在 markdown 中， 以下的内容都是同一个含义：
> 
> ```
> 1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
> 2. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
> 3. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。
> 
> 
> 1. **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
> 1. **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
> 1. **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。
> 
> 
> 
> -  **加强线上营销**：利用社交媒体和搜索引擎优化提升线上销售。
> -  **促销活动**：针对滞销产品进行打折促销，吸引客户购买。
> -  **客户关系管理**：增强与老客户的互动，提高客户满意度和忠诚度。
> ```

![image](https://github.com/user-attachments/assets/f6717316-989c-475f-ab24-55e71f0a8e53)
在官网的可以显示，本地引入显示不了序号且报错

**Comment by yangfuhai** [comment]
我当前的浏览器无法复现，麻烦给出具体的错误位置，或者可以联系我微信 fuh99888 远程看下。

**Comment by 2919807875** [comment]
> fuh99888

![image](https://github.com/user-attachments/assets/931554a9-e958-4cb2-8a4a-96a31d508df7)
报错位置
