### ISSUE TITLE
markdown 高亮内容无法保存和显示

### ISSUE THREAD

**Issue by wcmboy** [aieditor-team/AiEditor#118]
旧版本已经设置高亮container的内容，在最新版本1.2.7无法显示（内容是以markdown格式保存到数据库）
会直接显示
::: warning
xxxx
:::
的内容。
并且，在新版本编辑器中设置高亮内容是正常显示的，查看源代码的html也是有高亮的代码，但以markdown保存后，高亮的设置并没有转化成markdown保存，而是直接忽略了相当于没有设置高亮。

**Comment by yangfuhai** [comment]
修复代码已提交，下个版本支持。
