### ISSUE TITLE
使用setMarkdownContent动态插入表格内容报错

### ISSUE THREAD

**Issue by 2919807875** [aieditor-team/AiEditor#119]
使用setMarkdownContent动态插入表格内容报错：
markdownn内容：
![image](https://github.com/user-attachments/assets/2e4b51ae-5769-4242-b50b-bb9199a6f47d)
报错信息：
![image](https://github.com/user-attachments/assets/d703cb3c-9cc3-4888-bd21-1d8f44886659)

**Comment by 2919807875** [comment]
`# 销售数据表格

| 产品名称   | 销售数量 | 单价（元） | 总销售额（元） |
|------------|----------|------------|-----------------|
| 产品A     | 150      | 20         | 3000            |
| 产品B     | 200      | 15         | 3000            |
| 产品C     | 100      | 30         | 3000            |
| 产品D     | 50       | 50         | 2500            |
| **合计**   | **600**  |            | **11500**       |

> 表格说明：以上数据为2023年第一季度的销售情况，所有金额均为人民币。总销售额为各产品销售额的总和。`

**Comment by yangfuhai** [comment]
AIEditor 的版本是多少？

**Comment by 2919807875** [comment]
> AIEditor 的版本是多少？

1.2.8

**Comment by 2919807875** [comment]
> > AIEditor 的版本是多少？
> 
> 1.2.8

![image](https://github.com/user-attachments/assets/16acac9f-9b0d-4a1b-9f6a-01fc404d81d2)

**Comment by yangfuhai** [comment]
麻烦给一下 Makrdown 的元素内容

**Comment by yangfuhai** [comment]
我们验证插入如下的 Makrdown 并不会有任何问题。

```
# 销售数据表格

| 产品名称   | 销售数量 | 单价（元） | 总销售额（元） |
|------------|----------|------------|-----------------|
| 产品A     | 150      | 20         | 3000            |
| 产品B     | 200      | 15         | 3000            |
| 产品C     | 100      | 30         | 3000            |
| 产品D     | 50       | 50         | 2500            |
| **合计**   | **600**  |            | **11500**       |

> 表格说明：以上数据为2023年第一季度的销售情况，所有金额均为人民币。总销售额为各产品销售额的总和。
```

**Comment by 2919807875** [comment]
> 我们验证插入如下的 Makrdown 并不会有任何问题。
> 
> ```
> # 销售数据表格
> 
> | 产品名称   | 销售数量 | 单价（元） | 总销售额（元） |
> |------------|----------|------------|-----------------|
> | 产品A     | 150      | 20         | 3000            |
> | 产品B     | 200      | 15         | 3000            |
> | 产品C     | 100      | 30         | 3000            |
> | 产品D     | 50       | 50         | 2500            |
> | **合计**   | **600**  |            | **11500**       |
> 
> > 表格说明：以上数据为2023年第一季度的销售情况，所有金额均为人民币。总销售额为各产品销售额的总和。
> ```

![baoc](https://github.com/user-attachments/assets/6dc17f43-2d7c-428a-95f7-55fa6fea311c)

**Comment by yangfuhai** [comment]
你这个是通过 ai 插入一小段一小段的 Makrdown，并不是完整的 Makrdown。

**Comment by 2919807875** [comment]
> 你这个是通过 ai 插入一小段一小段的 Makrdown，并不是完整的 Makrdown。

对的

**Comment by yangfuhai** [comment]
这个错误是插入了不完整的 markdown 数据导致的，暂时不做处理。在插入 markdown 之前请先确保是完整的 markdown 数据。
