### ISSUE TITLE
【严重bug】添加图片markdown会自动添加:::，导致保存后图片无法显示

### ISSUE THREAD

**Issue by wcmboy** [aieditor-team/AiEditor#122]
<img width="698" alt="image" src="https://github.com/user-attachments/assets/504f2947-1a80-46a9-9f4a-335037608cda">

上传一张图片后，获取markdown打印出来如图，图片前后就会出现:::，markdown保存到数据库后，图片可以显示，但前后会有:::，如果再想编辑，编辑器中所有图片就无法显示了，跟丢失了一样。
<img width="676" alt="image" src="https://github.com/user-attachments/assets/7a5cf6e8-8767-4649-84d7-6f7f7d3552ce">
<img width="1310" alt="image" src="https://github.com/user-attachments/assets/b26f15d9-a000-4157-bee9-91bbee7cb7bc">

版本为：1.2.8

**Comment by wcmboy** [comment]
并且如果再次编辑，图片就显示不了了，再点保存的话，图片数据全部丢失

**Comment by yangfuhai** [comment]
已修复，下个版本发布。
