### ISSUE TITLE
markdown合并单元格失效

### ISSUE THREAD

**Issue by wcmboy** [aieditor-team/AiEditor#124]
1.2.9版本
在编辑模式下，表格合并单元格没有问题，但转化为markdown保存后，再显示时合并的单元格就失效，又被还原拆分了。

**Comment by yangfuhai** [comment]
> 1.2.9版本 在编辑模式下，表格合并单元格没有问题，但转化为markdown保存后，再显示时合并的单元格就失效，又被还原拆分了。

markdown 语法不支持单元格合并，非编辑器的问题。
