### ISSUE TITLE
markdown加粗如果结尾是标点符号，加粗会失效

### ISSUE THREAD

**Issue by wcmboy** [aieditor-team/AiEditor#125]
例如：正因为**钱是借来的，已经自带风险，还没有上战场，就已经增加了失败的风险**。何况股市风险本身就非常大。
如果加粗到句号前面，是没问题的。
但如果加粗到句号后面，
正因为**钱是借来的，已经自带风险，还没有上战场，就已经增加了失败的风险。**何况股市风险本身就非常大。
保存markdown后，就会直接把*号显示出来，加粗失效。
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/c96294b8-2cd2-4177-a5a7-1bcba27dc823" />

**Comment by yangfuhai** [comment]
正因为**钱是借来的，已经自带风险，还没有上战场，就已经增加了失败的风险。**何况股市风险本身就非常大。

**Comment by yangfuhai** [comment]
> 正因为**钱是借来的，已经自带风险，还没有上战场，就已经增加了失败的风险。**何况股市风险本身就非常大。

需要在末尾的 `**` 之后再添加一个空格才行，否则是不行的，github 也是如此。
