### ISSUE TITLE
希望增加图片编辑功能,比如添加超链接和alt自定义

### ISSUE THREAD

**Issue by undefined996** [aieditor-team/AiEditor#127]

**Comment by yangfuhai** [comment]
新版本已添加支持。

**Comment by undefined996** [comment]
感谢支持! 上周五实现了alt编辑, 还打算下周看下link咋实现.大佬这么快就支持了...
除了购买商业版,我觉得可以加个收款二维码,能让个人开发者给大佬尽一份绵薄之力.

**Comment by yancey2025** [comment]
图片属性、链接怎么配置
bubbleMenuItems: ["AlignLeft", "AlignCenter", "AlignRight", "delete"]
目前网站 API 只看到这四个
