### ISSUE TITLE
翻译的结果，点击append或者replace回出现问题

### ISSUE THREAD

**Issue by abearxiong** [aieditor-team/AiEditor#129]
<img width="494" alt="image" src="https://github.com/user-attachments/assets/dec22246-5dbe-4ee2-b092-c03a7fd02538" />

操作

<img width="401" alt="image" src="https://github.com/user-attachments/assets/7cbb5b41-1723-410c-81d5-e311346fee7a" />

**Comment by yangfuhai** [comment]
不建议自己编译版本来使用，有可能会触发 LGPL 开源协议限制而涉及代码侵权，使用 npm 安装使用不会出现这个问题。

**Comment by abearxiong** [comment]
这是因为里面包函了<content></conent>的标签啥的，导致md2html有问题好像。over
