### ISSUE TITLE
提及功能有显示问题

### ISSUE THREAD

**Issue by ouronghuang** [aieditor-team/AiEditor#132]
在文档 [提及-返回昵称和用户 ID](https://aieditor.dev/docs/zh/config/mention.html#%E8%BF%94%E5%9B%9E%E6%98%B5%E7%A7%B0%E5%92%8C%E7%94%A8%E6%88%B7-id) 中说

> 可以返回一个对象，包含有 label 和 id 字段

但是实际测试以及翻阅源码发现，除了需要 label 和 id 字段之外，还需要 name 字段才能完整的显示

```js
const data = [
  {
    id: 1,
    label: 'Michael Yang',
    name: 'Michael Yang'
  }
];
```

**Comment by yangfuhai** [comment]
修复代码已提交了：https://github.com/aieditor-team/AiEditor/commit/5e795d5502f188e87f2f5ecf956ff994db76bca0
