### ISSUE TITLE
vue3 全屏按钮有bug

### ISSUE THREAD

**Issue by ashuicoder** [aieditor-team/AiEditor#14]
点击全屏按钮不是全屏
![image](https://github.com/aieditor-team/AiEditor/assets/47807522/878ef185-adde-41c5-94aa-20148105a096)

**Comment by ashuicoder** [comment]
我看了下源码
![image](https://github.com/aieditor-team/AiEditor/assets/47807522/17ce1ac5-362f-4e97-896a-8599431f5ef3)
全屏应该是直接调用浏览器的api，而不是自己写样式，我出现这个问题的原因应该就是样式冲突了

**Comment by yangfuhai** [comment]
可以来个 pr

**Comment by yangfuhai** [comment]
感谢 pr
