### ISSUE TITLE
大部分api方法返回值为空怎么处理

### ISSUE THREAD

**Issue by gaoyulin7866** [aieditor-team/AiEditor#18]
<img width="693" alt="image" src="https://github.com/aieditor-team/AiEditor/assets/28721559/ba0a965c-7740-4443-bd8d-1b0e07e89858">
<img width="571" alt="image" src="https://github.com/aieditor-team/AiEditor/assets/28721559/8ad28815-7218-4f0f-9ad7-d06041211016">

**Comment by yangfuhai** [comment]
无法复现。
