### ISSUE TITLE
AI 翻译会出错，而且复制粘贴时，无法粘贴图片。

### ISSUE THREAD

**Issue by auendx** [aieditor-team/AiEditor#2]
试用了一下，目前还存在3个大问题希望后续作者能改善：

1、AI翻译时会破坏格式，同时翻译内容会出错，建议可以自定义国内或免费的翻译API接口功能。
2、从网页上复制，再到AiEditor中粘贴时，只能粘贴出文字内容，无法粘贴图片或其它格式。
3、后续可否打包成 exe 或 单文件本地运行？ 

目前很棒的功能：
1、格式刷功能。
2、字体选择和高亮颜色选择。
3、集成AI功能（还需进一步优化），最好还加上代码补充注释功能。

谢谢！   

After trying it out, there are still three big problems that I hope the author can improve in the future:

1. AI translation will destroy the format and the translation content will be wrong. It is recommended to customize the domestic or free translation API interface function.
2. When copying from a web page and pasting it into AiEditor, only text content can be pasted, and pictures or other formats cannot be pasted.
3. Can it be packaged into an exe or a single file and run locally?

Great features so far:
1. Format brush function.
2. Font selection and highlight color selection.
3. Integrate AI functions (needs further optimization), and it is best to add code supplementary annotation functions.

Thanks!

**Comment by yangfuhai** [comment]
fixed
