### ISSUE TITLE
图片参数

### ISSUE THREAD

**Issue by Teeoo** [aieditor-team/AiEditor#20]
![image](https://github.com/aieditor-team/AiEditor/assets/25023667/bbf62cf2-90e6-4294-bdb3-3cd1d7217f4a)

可参考下[wangeditor](https://www.wangeditor.com/demo/index.html)

`image`中的`defaultSize`不应该是`number`类型，比如说我需要个百分比，你这边给的默认参数是px

**Comment by Teeoo** [comment]
希望可以开放更多参数

**Comment by kimsmel** [comment]
你直接传字符串`100%` 其实也是可以的

**Comment by yangfuhai** [comment]
已支持
