### ISSUE TITLE
上传图片时允许自定义请求参数image=>files

### ISSUE THREAD

**Issue by chatty-go** [aieditor-team/AiEditor#21]
原始请求：
<img width="393" alt="7174fddaaa335cc23017fc95727d0f41" src="https://github.com/aieditor-team/AiEditor/assets/8198638/356fd474-5485-40d4-8504-1d1a6c0b060b">

请求后端时，参数为image

期望增加一个属性，可以替换这个image，如改为 files。

因为后端接口是现成的，跟这个参数可能不匹配。

目前只测试了图片上传，附件上传和视频上传如果也是一样的，期待能一起调整。

**Comment by yangfuhai** [comment]
代码 已 push，下个版本支持。
