### ISSUE TITLE
图片上传设置uploadFormName参数无效

### ISSUE THREAD

**Issue by chatty-go** [aieditor-team/AiEditor#27]
版本："aieditor": "^1.0.0"

问题现象：
![image](https://github.com/aieditor-team/AiEditor/assets/8198638/6003af29-b69d-4830-b388-b6c06c6a203f)

提示参数uploadFormName不存在，在实际上传的时候也没有修改成功。

期望：uploadFormName设置的参数能替换默认的image值

**Comment by yangfuhai** [comment]
新版本已修复。
