### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by GZ315200** [aieditor-team/AiEditor#28]
Module parse failed: Unexpected token (16:28)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   onMounted(() => {
|     new AiEditor({
>       element: divRef.value as Element,
|       placeholder: "点击输入内容...",
|       content: 'AiEditor 是一个面向 AI 的开源富文本编辑器。 ',

**Comment by yangfuhai** [comment]
新版本测试无法复现。

**Comment by buzheng666** [comment]
遇到了同样的问题
