### ISSUE TITLE
选中文本后删除，会多删除一个字符

### ISSUE THREAD

**Issue by wcmboy** [aieditor-team/AiEditor#30]
![2024-05-29 102514](https://github.com/aieditor-team/AiEditor/assets/1540087/00594de2-a426-41ee-9437-06c1a1b2dc8e)

选中几个文本，删除时，会多删除一个字符。

https://github.com/aieditor-team/AiEditor/assets/1540087/b70b992b-cd8f-4328-ae7c-4068bad8da68

**Comment by yangfuhai** [comment]
先强制刷新一下浏览器看，可能有旧版本缓存。目前测试 http://aieditor1.jpress.cn/ 并未发现这个问题。

**Comment by wcmboy** [comment]
原来是浏览器插件造成的，关闭后就正常了。
