### ISSUE TITLE
react-ts示例中，如何添加章节目录功能

### ISSUE THREAD

**Issue by Summersumm** [aieditor-team/AiEditor#34]
![image](https://github.com/aieditor-team/AiEditor/assets/40738034/61b38555-5f55-4624-8c89-3257b4865c2f)
![image](https://github.com/aieditor-team/AiEditor/assets/40738034/a21dc2f1-dee5-4a95-836f-bef2cdf5df7b)

**Comment by qsx9527** [comment]
根据官方示例[https://github.com/aieditor-team/AiEditor/blob/main/demos/docs-ts/index.html](https://github.com/aieditor-team/AiEditor/blob/main/demos/docs-ts/index.html)
自定义布局时需要添加
![image](https://github.com/aieditor-team/AiEditor/assets/79394370/f2b19f58-63af-4f55-9c4a-a167fcf58dff)
以及引入时[https://github.com/aieditor-team/AiEditor/blob/main/demos/docs-ts/src/main.ts](https://github.com/aieditor-team/AiEditor/blob/main/demos/docs-ts/src/main.ts), 需要updateOutLine()函数功能
![image](https://github.com/aieditor-team/AiEditor/assets/79394370/72018202-7ffe-4019-8b0c-cc318a2b002f)

**Comment by Summersumm** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Summersumm** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
