### ISSUE TITLE
本项目的LGPL许可是否能用于商业项目，并对公众开放

### ISSUE THREAD

**Issue by blvyoucan** [aieditor-team/AiEditor#43]
一直不理解LGPL，请大佬解惑下。

看到这个项目感觉很不错，但是用的LGPL许可，不太清楚是否能用于自己的项目。

使用场景是吧aieditor通过npm引入到我的web项目中（不涉及对aieditor的修改），使用vue框架打包发布，然后提供给互联网上的用户使用。

疑惑1：这属于静态链接，还是动态链接？

疑惑2：我是否要开源我自己的web项目？

疑惑3：是否需要在我的web项目中提供aieditor的github链接以及LGPL协议原文？

**Comment by yangfuhai** [comment]
通过 NPM  install  AIEditor 的方式来使用 AIEditor，不会导致 GPL 传染，可以用于商业目的。

但是，如果基于源码自行编译（可能对源码修改、新增或删除功能），则可能会受限于与 LGPL 而无法商用。

增对你的场景，是基于 npm install 的方式，引入到你的 web 项目中，则可以商用。或者把你自己的项目打包、分享给互联网的任何用户。

**Comment by blvyoucan** [comment]
> 在V2看到的。 不能以 LGPL 协议的AiEditor代码为基础，通过修改和衍生的方式做二次开发的商业软件采用。。
> 
> 正确姿势：在开源网站上 公布 继承 LGPL 协议的AiEditor衍生版本，然后单独编译出该衍生体的静态库，加入主程序进行链接，最后在主程序的设置页面，添加 License 的说明即可。

感觉是衍生版本的衍生版本，是不是还是的遵循LGPL?
