### ISSUE TITLE
粘贴图片时会出现缩略图

### ISSUE THREAD

**Issue by yangcheng0111** [aieditor-team/AiEditor#46]
![b819f88f9488a9ea8b68ff247681ed68](https://github.com/aieditor-team/AiEditor/assets/167048233/2fba886f-ae5f-4af4-87bf-6fba2cdd0381)
在粘贴图片时会出现
，一个小的缩略图，点击图片按钮不会

**Comment by yangfuhai** [comment]
新版本已修复。
