### ISSUE TITLE
编辑器中获取的html代码如何做到和编辑器中的样式一样

### ISSUE THREAD

**Issue by leyan-lian** [aieditor-team/AiEditor#47]
编辑器中的图片是一张图片一行，获取的html代码没有换行。给图片设置居中，居右后，获取的html代码 居中不管用。
![17f45f15f281b0b6374ae8fcc90e59b2](https://github.com/aieditor-team/AiEditor/assets/92238151/c565c101-a146-4775-82a6-8bbf5683718d)
![ede52d42a8d0de76971518f08b4b2a66](https://github.com/aieditor-team/AiEditor/assets/92238151/71646e5a-0164-472c-b47b-abda939366b1)
![72ef750aa6a08108e81bb4dbea58474b](https://github.com/aieditor-team/AiEditor/assets/92238151/52f5d0d5-1621-433b-b210-c82b342ab2b8)

**Comment by Alan-Echo** [comment]
我也遇到了一样的问题，发现`getHtml()`拿到的内容没有换行居中那些样式，你后来解决了吗？

**Comment by leyan-lian** [comment]
> 我也遇到了一样的问题，发现`getHtml()`拿到的内容没有换行居中那些样式，你后来解决了吗？

没有，我换别的了

**Comment by yangfuhai** [comment]
@Alan-Echo  @leyan-lian 升级到最新版本，更新最新代码即可解决。

**Comment by Alan-Echo** [comment]
> @Alan-Echo @leyan-lian 升级到最新版本，更新最新代码即可解决。

大佬，我升级到1.0.14版本后，还是一样的结果啊，我想要看预览效果，这是我做的编辑器
![image](https://github.com/user-attachments/assets/da06907f-d2e8-4ff6-a056-a9afce8be583)
左侧是输入区域，右侧是预览区域，预览区域目前使用的是只读模式，发现图片样式还是有问题。使用v-html和编辑器只读模式是一样的效果,图片是没有居中效果的，当图片和文字混合排版，图片右对齐时，图片看起来时有个浮动效果，就和文字的上下层级就不正确
这是使用v-html的效果
![image](https://github.com/user-attachments/assets/d49ee2b3-e3a2-46ba-8d3b-d2906a261fc4)

是我使用的方式不对吗？
我初始化编辑器的代码
```html
<div class="editor" ref="divRef"/>
```
```js
aiEditor = new AiEditor({
        element: divRef.value as Element,
        placeholder: "Click to Input Content...",
        content: htmlContentList[htmlDataStore.index].content,
        toolbarKeys: ["undo", "redo", "brush", "eraser",
            "|", "heading", "font-family", "font-size",
            "|", "bold", "italic", "underline", "strike", "link", "code", "subscript", "superscript", "hr", "todo", "emoji",
            "|", "highlight", "font-color",
            "|", "align", "line-height",
            "|", "bullet-list", "ordered-list", "indent-decrease", "indent-increase", "break",
            "|", "image", "video", "attachment", "quote", "code-block", "table",
            "|", "source-code", "printer", "fullscreen", "ai",
            {
                html: "<div style='color: red;'>自定义按钮</div>",
                onClick: (event: any, editor: any) => {
                    //点击事件
                    console.log('自定义按钮', event, editor)
                },
                tip: "鼠标移动上去的提示内容",
            }
        ],
        image: {
            allowBase64: false
        }
    });```

预览时的方式
1. 只读模式
```html
<div ref="viewRef"></div>
```
```js
aiViewEditor = new AiEditor({
        element: viewRef.value as Element,
        editable: false,
        content: htmlContentList[htmlDataStore.index].content,
    })
```

2. v-html
2.1 外层没有包含其他class
```html
 <div v-html="htmlContent"></div>
```
2.2 外层包含其他样式，是通过f12查看原编辑器的样式找到的
```html
<div class="aie-theme-light">
    <div class="aie-container">
        <div class="tiptap ProseMirror aie-content" v-html="htmlContent">
        </div>
    </div>
</div>
```

**Comment by Alan-Echo** [comment]
> > 我也遇到了一样的问题，发现`getHtml()`拿到的内容没有换行居中那些样式，你后来解决了吗？
> 
> 没有，我换别的了

@leyan-lian 大佬后来换哪个编辑器啦？

**Comment by leyan-lian** [comment]
> > > 我也遇到了一样的问题，发现`getHtml()`拿到的内容没有换行居中那些样式，你后来解决了吗？
> > 
> > 
> > 没有，我换别的了
> 
> @leyan-lian 大佬后来换哪个编辑器啦？

TinyMCE

**Comment by yangfuhai** [comment]
@Alan-Echo @leyan-lian 感觉像是没有升级到最新版本，还用了旧的版本，14 版本专门修复了这个问题的。 另外 TinyMCE 是基于 GPL 开源协议，在使用 GPL 开源软件的时候，需要注意 GPL 传染，GPL 传染的情况下，需要你的软件也必须是使用 GPL 协议才能正常使用，否则就是侵权的。

**Comment by leyan-lian** [comment]
> @Alan-Echo @leyan-lian 感觉像是没有升级到最新版本，还用了旧的版本，14 版本专门修复了这个问题的。 另外 TinyMCE 是基于 GPL 开源协议，在使用 GPL 开源软件的时候，需要注意 GPL 传染，GPL 传染的情况下，需要你的软件也必须是使用 GPL 协议才能正常使用，否则就是侵权的。

嗯嗯，我本地测试使用的，没有上线盈利。

**Comment by yangfuhai** [comment]
@Alan-Echo @leyan-lian 图片的外部应该有一个 div，可以通过 css 去设置这个 div 的样式。

**Comment by Alan-Echo** [comment]
> @Alan-Echo @leyan-lian 图片的外部应该有一个 div，可以通过 css 去设置这个 div 的样式。

@yangfuhai 好的，感谢大佬
