### ISSUE TITLE
image 配置 customMenuInvoke自定义选择图片后，怎么插入多张图片？

### ISSUE THREAD

**Issue by ImpChiang** [aieditor-team/AiEditor#54]
试过` dispatch(tr.insert(selection.from,schema.nodes.image.create(src: '')))`，只能是单张图插入

**Comment by yangfuhai** [comment]
多次循环调用 就可以呀

**Comment by ImpChiang** [comment]
已解决，将多个选中图片组成image标签后拼接成一个html字符串，insert插入即可
