### ISSUE TITLE
code-block 自定义代码类型

### ISSUE THREAD

**Issue by naiheyoung** [aieditor-team/AiEditor#55]
代码块是否可以自定义代码类型呢
如 `prismjs` 标准, nginx类型、vim类型等
![image](https://github.com/user-attachments/assets/825af87f-9897-4684-b64a-0842a77fffdd)
使用markdown语法 ```nginx 不在给定的代码块类型中 会默认转换为 `auto`
有无其他解决方案呢

**Comment by yangfuhai** [comment]
可以来个 pr

**Comment by yangfuhai** [comment]
已经添加了自定义代码块语言类型的支持
