### ISSUE TITLE
会支持 AI 模型切换和配置么？

### ISSUE THREAD

**Issue by zhengxs2018** [aieditor-team/AiEditor#6]
项目挺不错的，我在找一个自用的富文本编辑器，目前看到是星火的，希望能加一个切换其他模型的，方便对比内容。

如果支持，我可以帮忙把其他模型接进来，这是我写的 [通用 AI SDK](https://github.com/zhengxs2018/ai) 模块，但可以直接将代码集成进来，而不是模块。

可参考我给同类的 [unit-mesh/b3](https://github.com/unit-mesh/b3) 项目，就是直接代码迁移过去使用的。

**Comment by yangfuhai** [comment]
非常欢迎 pr，目前就 AIEditor 来说，对于 Ai 接口的抽象封装还没有开始，看到您写的 https://github.com/zhengxs2018/ai 非常不错，是否可以基于您这个项目的理念，对目前的 ai 进行抽象封装？

**Comment by zhengxs2018** [comment]
可以试试
