### ISSUE TITLE
图片的属性使用了algin属性进行布局，这是一个已经弃用的属性，在不同的浏览器里可能会造成布局异常

### ISSUE THREAD

**Issue by chaofanat** [aieditor-team/AiEditor#63]
![image](https://github.com/user-attachments/assets/da08e970-f284-4a7a-b1d0-181adcdb421d)

将html代码单独放在html文件里后：
![image](https://github.com/user-attachments/assets/06e86ec5-6d65-40da-9627-b2560c07d0eb)

应该使用更合适的方式进行布局的处理。

**Comment by yangfuhai** [comment]
代码已提交，下个版本修复。
