### ISSUE TITLE
Feature request: Added comments by AI

### ISSUE THREAD

**Issue by maxmannen** [aieditor-team/AiEditor#64]
This is a very competent and easy to use editor. Very good work by you all!
Is it possible to implement an AI tool that creates comments (automatic or by request)? 
If I could dream on I would like to have the possibility to mark comments as "good" or "bad" so I could use that for training the LLM.

**Comment by yangfuhai** [comment]
This requirement may not be a "popular" one, and it is completely fine from a technical point of view. However, because this requirement is relatively unique, we may not add this feature to AIEditor.
