### ISSUE TITLE
Add paste_as_text functionality

### ISSUE THREAD

**Issue by TobiasKrais** [aieditor-team/AiEditor#76]
TinyMCE has an option "paste_as_text: true," when initializing the editor. Please add a similar funcitonality to the editor.

**Comment by yangfuhai** [comment]
this feature  is completed by https://github.com/aieditor-team/AiEditor/commit/eb2bf1f30b2e0a98269e20942b7f7ac377ea75b0

**Comment by TobiasKrais** [comment]
Thanks a lot! You're a great team!
