### ISSUE TITLE
vue2 + js ,没有使用ts的项目怎么配置？ 目前是报错,如下：

### ISSUE THREAD

**Issue by mylwl520** [aieditor-team/AiEditor#93]
error  in ./node_modules/aieditor/dist/index.js

Module parse failed: Unexpected token (4768:39)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       return e ? this.replaceSelectionWith(i.text(e), !0) : this.deleteSelection();
|     {
>       if (r == null && (r = n), r = r ?? n, !e)
|         return this.deleteRange(n, r);
|       let s = this.storedMarks;

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/homePage/HomePage.vue?vue&type=script&lang=js 3:0-36
 @ ./src/views/homePage/HomePage.vue?vue&type=script&lang=js
 @ ./src/views/homePage/HomePage.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.6.75:8888&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by yangfuhai** [comment]
升级 node 到 v20，以及升级 babel 到最新版本。
