### ISSUE TITLE
Enlarge icons in toolbar

### ISSUE THREAD

**Issue by TobiasKrais** [aieditor-team/AiEditor#95]
Icons in toolbar are only 16x16px. Default icon size in other editors are 24x24px. Please enlarge icons or add configuration option to set small (current) medium (24x24px) and large (32x32px) icon size.

**Comment by yangfuhai** [comment]
The latest version already supports it. You can refer to the following document for configuration: https://aieditor.dev/config/toolbar.html#set-toolbar-button-size
