### ISSUE TITLE
图片大小问题

### ISSUE THREAD

**Issue by xuwuruoshui** [aieditor-team/AiEditor#97]
上传图片后，拖动图片修改大小，value没有被监控到。然后uploaderEvent的onSuccess设置图片参数，只有src、alt 生效，align和width都没有生效。

**Comment by xuwuruoshui** [comment]
markdown没有设置上，但是html里面还是有的。编辑时加载markdown，样式就没了

**Comment by yangfuhai** [comment]
> markdown没有设置上，但是html里面还是有的。编辑时加载markdown，样式就没了

@xuwuruoshui 不建议存储为 markdown，因为 makrdown 语法的原因，无法保留所有的编辑细节和属性。

**Comment by xuwuruoshui** [comment]
编辑的时候我看示例是加载的markdown的文本，如果要再编辑样式就没有了

**Comment by xuwuruoshui** [comment]
![image](https://github.com/user-attachments/assets/643a6a4d-5662-4117-a9f8-e3083c91c761)
理解了，就还是不要用markdown了，markdown只作为输入的一种方式，html也是一种输入方式。存储统一用html就ok。
