### ISSUE TITLE
回显图片无法正常显示，只能显示文本

### ISSUE THREAD

**Issue by kimsmel** [aieditor-team/AiEditor#99]
<img width="1591" alt="image" src="https://github.com/user-attachments/assets/9c6a6b0c-96b9-4242-9994-9678280de69e">

aiEditor版本：1.2.0

Vue3：3.3.4

Chrome：130.0.6723.58

**Comment by yangfuhai** [comment]
代码已提交，下个版本修复。

**Comment by kimsmel** [comment]
> 代码已提交，下个版本修复。

感谢作者，辛苦了
今天我升级后查看还是和昨天一样，目前是1.2.1版本，试了上传图片，还是会被p标签包裹
回显图片还是不会渲染呢，奇怪

**Comment by rt-bear** [comment]
mark

**Comment by rt-bear** [comment]
升级到了1.2.2版本，还是无法回显图片，
大佬赶紧fix呀，急着上线，十万火急@kimsmel

**Comment by yangfuhai** [comment]
> 升级到了1.2.2版本，还是无法回显图片， 大佬赶紧fix呀，急着上线，十万火急@kimsmel

你的初始化代码是什么样的呢

**Comment by rt-bear** [comment]
重新上传一次的用div标签包裹的可以正常显示了，之前用p标签包裹的没显示出来。。。。
一直用mock数据来着，sorry
